### ISSUE TITLE
I have installed khalti plugin as shown in documentation 

### ISSUE THREAD

**Issue by mohak8525** [khalti/khalti-flutter-sdk#14]
This is giving me an error of khaltiLocalization.
![WhatsApp Image 2021-11-18 at 2 57 08 PM](https://user-images.githubusercontent.com/93791618/142471545-6413d9db-9914-4ceb-a896-53ef9d381517.jpeg)

![WhatsApp Image 2021-11-18 at 3 08 41 PM](https://user-images.githubusercontent.com/93791618/142471587-ec74c675-4737-4530-8081-cfeb5a0f7f6c.jpeg)

So please lets have a look into this.

**Comment by sarbagyastha** [comment]
Hi @mohak8525 , you need to add `KhaltiScope` in the topmost widget of your app, above your main `MaterialApp`.

**Comment by sarbagyastha** [comment]
Closing for now. Please reopen if the issue still exists.
