### ISSUE TITLE
Issue with CORS on flutter web.

### ISSUE THREAD

**Issue by chasseuragace** [khalti/khalti-flutter-sdk#20]
Accessing the APIs when running on Browser is not possible due to CORS.

1. Build/Run the example app on Web

Whats expected:
Successful API requests 
How? 
include in response the origin from the request header.

**Comment by acpmasquerade** [comment]
This is KPG-v1 and this version of SDK is no longer maintained and already in the deprecation schedule.

Please upgrade to KPG-v2 checkout version
https://github.com/khalti/checkout-sdk-flutter
