### ISSUE TITLE
Issue on eBanking and mobileBanking payment preference

### ISSUE THREAD

**Issue by solarurja** [khalti/khalti-flutter-sdk#21]
**Describe the bug**
Throws ImageStreamListener error while navigating to eBanking or mobileBanking tab and whole app freezes.

**To Reproduce**
1. Enable PaymentPreference.eBanking or PaymentPreference.mobileBanking preferences using KhaltiScope.of(context).pay(preferences: []).
2. Tap on eBanking or mobileBanking tab.
3. ImageStreamListener exception thrown from image.dart

**Device Information (please complete the following information):**
 - Device: Android emulator (android 11.0)

**Additional context**
Error may have been thrown as there are some thumbnails images missing for few banks. Proper inclusion of image thumbnail may help.

**Comment by acpmasquerade** [comment]
This is KPG-v1 and this version of SDK is no longer maintained and already in the deprecation schedule.

Please upgrade to KPG-v2 checkout version
https://github.com/khalti/checkout-sdk-flutter
