### ISSUE TITLE
Error while using other payment options apart from Khalti.

### ISSUE THREAD

**Issue by josephyaduvanshi** [khalti/khalti-flutter-sdk#27]
**Describe the bug**
When using the other payment preferences apart from khalti, it redirects to kpg:// instead of https:// which causes error while processing the request

**To Reproduce**
1. call the  KhaltiScope.of(context).pay([all the preferences]) and enter the amount in the text field and click pay.

**Screenshots**
![Screenshot_20221016_101918](https://user-images.githubusercontent.com/97875347/196018392-47043b4d-3ff8-4b8b-b144-05b992381ae5.jpg)

**Device Information (please complete the following information):**
 - Device: Vivo z1 pro
 - OS: Android 11, FUNTOUCH OS
 - Version latest

**Comment by subarnaPdl** [comment]
I'm facing similar issue. Any updates?

**Comment by acpmasquerade** [comment]
This is KPG-v1 and this version of SDK is no longer maintained and already in the deprecation schedule.

Please upgrade to KPG-v2 checkout version
https://github.com/khalti/checkout-sdk-flutter
