### ISSUE TITLE
Outdated Dependencies - Need Update for Compatibility

### ISSUE THREAD

**Issue by bishal-rumba007** [khalti/khalti-flutter-sdk#36]
I appreciate your work on `khalti_flutter`. Currently, it has a dependency on `intl` with a constraint of `^0.18.0`. The stable version is now `0.19.0`, causing compatibility issues for users on the latest Flutter versions.

### Issue Details
- Package: khalti_flutter
- Version: 3.0.0
- Outdated Dependency: intl
- Constraint: ^0.18.0
- Latest Stable Version: 0.19.0

### Request
I personally have been using the package by downgrading the int version to 0.18.1, 
Please consider updating the dependency to ensure compatibility with the latest Flutter versions.

**Comment by acpmasquerade** [comment]
Hello @bishal-rumba007 
Thank you for the appreciation. 

To add more, 
this is KPG-v1 and this version of SDK is no longer maintained and already in the deprecation schedule.

Please upgrade to KPG-v2 checkout version
https://github.com/khalti/checkout-sdk-flutter
