### ISSUE TITLE
🐛Bug : The color of the Khalti scope UI button does not alter as anticipated.

### ISSUE THREAD

**Issue by Dev00kushal** [khalti/khalti-flutter-sdk#38]
**Describe the bug**
The Khalti scope UI button color does not change as expected.

**Expected behavior**
The button color should be Colors.purple but it is not changing it is kind of weird ☹️.

**Screenshots**
![image](https://github.com/khalti/khalti-flutter-sdk/assets/127578046/001fbbd7-483d-40d9-b22e-a48f6957352e)
![image](https://github.com/khalti/khalti-flutter-sdk/assets/127578046/5c2d6bc5-4a4f-41c1-8030-4dc593b266c5)

**Comment by acpmasquerade** [comment]
This is KPG-v1 and this version of SDK is no longer maintained and already in the deprecation schedule. 

Please upgrade to KPG-v2 checkout version
